# Generated by Django 5.1.6 on 2025-05-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], default='M', max_length=1, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('L', 'Lembrete'), ('E', 'Evento'), ('N', 'Nota'), ('M', 'Meta')], default='L', max_length=1, verbose_name='Tipo da Tarefa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Criado'), ('E', 'Em andamento'), ('F', 'Finalizado')], default='C', max_length=1, verbose_name='Status'),
        ),
    ]
